spring:
  datasource:
    url: jdbc:mysql://apprentice.cgzz7jhrx4km.ap-northeast-2.rds.amazonaws.com:3306/BOARD?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: board
    password: boardQwer!@34%^
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 110583518840-lfh7bsa0fdobld5a41vi98ilji56sctq.apps.googleusercontent.com
            client-secret: 5psD6VAf5_h7C2-bHrB4jacb
            scope: profile, email

server:
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true